worker_processes auto;

events {
    worker_connections 10240;
}

# 核心：Stream 模块专用于四层负载均衡（TCP/UDP）
stream {
    upstream dns_nodes {
        # 默认使用轮询 (Round Robin) 算法
        server dns-node-1:8053;
        server dns-node-2:8053;
        server dns-node-3:8053;
    }

    server {
        listen 53 udp; # 对外监听 53 端口
        proxy_pass dns_nodes;
        proxy_timeout 1s;    # UDP 代理超时时间
        proxy_responses 1;   # 预期上游返回 1 个包就结束会话
    }
}