apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dns-firewall

resources:
  - ../../base

replicas:
  - name: dns-firewall
    count: 5

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: dns-firewall-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 30
  - target:
      kind: Deployment
      name: dns-firewall
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
