apiVersion: v1
kind: Secret
metadata:
  name: dns-firewall-secret
  namespace: dns-firewall
type: Opaque
stringData:
  mysql-root-password: "dns-root-password"
  mysql-password: "dns-password"
  mysql-user: "dns_user"
  redis-password: ""
